export { default as GlobalStyle } from './GlobalStyle';
export { default as Navbar } from './Navbar';
export { default as AboutSection } from './AboutSection';
export { default as ServicesSection } from './ServicesSection';
export { default as FaqSection } from './FaqSection';
export { default as Wave } from './Wave';
export { default as Toggle } from './Toggle';
export { default as Movie } from './Movie';
export { default as ScrollTop } from './ScrollTop';
